### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ttanimichi** [ttanimichi/dnd-example#11]
## リリースブロッカー

- [ ] ドラッグ＆ドロップのパフォーマンスチューニング
  - [x] プロファイラ調査
    - [ ] React DevTools
    - [ ] Chrome devtools: Performance
    - [ ] Chrome devtools: Performance Insight
    - [ ] Lighthouse
  - [ ] 計測
- [ ] ショッピングカートを動くようにする
- [ ] カードのデザインを整える
- [ ] Rails への組み込み

## nice to have

- [ ] undo, redo にショートカットキーを割り当てる
- [ ] 初回表示時に動画で使い方を解説するモーダルを表示する
- [ ] Unit Test の整備
- [ ] コードレビューとその修正
